name: Linter check

on: push

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  linter_check:
    name: Format, Lint & Typos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install Rust stable toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Install Protobuf Compiler
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Run Fmt check
        run: cargo fmt -- --check

      - name: Run Clippy check
        run: cargo clippy --all-features

      - name: Check typos
        uses: crate-ci/typos@master